[build.environment]
  NODE_VERSION = "20"

[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
